### ISSUE TITLE
Debouncing

### ISSUE THREAD

**Issue by ReinierMaas** [Kipke/InteractieTech#12]

**Comment by Kipke** [comment]
The reason you're ending up in the cleaning menu probably has something to do with the millis rollover issue (#2). 
That causes UNKNOWN to immediately go to CLEANING. So if your door is open you immediately go from (menu to) stand-by to unknown to cleaning. 

So I think you should fix #2 before continuing to check if there is something wrong with the debounce.

**Comment by ReinierMaas** [comment]
I am gonna test this to check if this works now
