### ISSUE TITLE
Actuator connection needs different port

### ISSUE THREAD

**Issue by Kipke** [Kipke/InteractieTech#14]
When the actuator is connected to port 13 it flashes on startup(and thus firing a few shots)

I think we should use port A0, as we are not going to use that sensor.

**Comment by ReinierMaas** [comment]
It won't fire a shot if it is within 15 second range right?

**Comment by Kipke** [comment]
For me it starts shooting immediately when it gets a pulse. So yes it needs to be on another port.

**Comment by ReinierMaas** [comment]
Haha okay then we need to change this

**Comment by ReinierMaas** [comment]
Misschien een setup met alle nieuwe pinnen online zetten

**Comment by Kipke** [comment]
Closed in 1a8e10e3165db31ab9baceb89c508158b96272be
