### ISSUE TITLE
Finish the menu

### ISSUE THREAD

**Issue by Kipke** [Kipke/InteractieTech#16]
Add an exit  option, so you don't have to wait for the timeout.

Remove the degradation options, unless we are going to implement it.

Also how do you get the values back down again, can I only increase the times and everything?

**Comment by ReinierMaas** [comment]
At 600 sec (10 minutes) there is a loop around

**Comment by ReinierMaas** [comment]
It is the triggered that is going to need to scan for movement and degredate at that value exceeding the degradation time
