### ISSUE TITLE
Video walkthrough

### ISSUE THREAD

**Issue by ReinierMaas** [Kipke/InteractieTech#18]
You need to create a video of approximately 3 minutes (anything between 2:50 and 3:10 will do) offering a walkthrough of your smart interactive automatic toilet freshener. It should at least cover the following topics:

The features of your system from a hardware-technical point of view. What hardware setup do you use? Which components are used for what purpose? How are they interconnected?
The features of your system from a software-technical point of view. How does the sketch work? Which libraries do you use? How do you handle the challenges posed by the limitations (memory, timers, interrupts, lack of threads, etc.) of the platform?
The features of your system from a functional point of view. How does it behave? How smart is it? What about its interactivity? What extra functionality did you implement, if any?
A demonstration of your system functioning in its ‘natural environment’, including mounting details, to show that you actually built it and used it. If you’re working with a fellow student on this assignment, it needs to be it installed in only one location.
Some reflection on your system. Does it work? How robust is it? What were the difficulties? Which choices did you make? Would you build it again in the same way? What went well and what would you change?
Feel free to add additional topics, such as a review by one or two actual users of your system, but don’t exceed the 3:10 time limit.

We are not looking for high production values in terms of video editing, resolution and camera quality, but make sure that things are clear. The video basically has to convince us of the quality and the quantity of the work that you did for this assignment and whether or not you meet the objectives.

**Comment by ReinierMaas** [comment]
Video walkthrough. You’ll need to upload your video walkthrough to a public video site (YouTube, Vimeo) and create a readme.txt text file containing the link to your video walkthrough.

**Comment by Kipke** [comment]
http://youtu.be/HQjeU88g8Uo
