### ISSUE TITLE
Description

### ISSUE THREAD

**Issue by ReinierMaas** [Kipke/InteractieTech#19]
You need to write a 6 to 8 page paper which describes the functional and technical features and details of your smart interactive automatic toilet freshener, including the process of building it and a reflection on its success (or lack thereof). This description allows you to elaborate on the topics covered in your video. Use it to add detail to these topics and/or cover topics which could not be covered in the video, time-wise. But please make sure that the description can be read stand-alone: if one only has the description, it should be clear what you’ve built, how you’ve built it, why you’ve built it that way and whether you think building it was a good idea. Be sure to include a state diagram of your system (no specific format required). Please do add pictures to illustrate certain points.

**Comment by ReinierMaas** [comment]
Description. The paper containing the description of your system should be a pdf file.

**Comment by ReinierMaas** [comment]
Ik doe menu en triggered stuk schrijven

**Comment by Kipke** [comment]
Ik doe flowchart & schematic

**Comment by ReinierMaas** [comment]
okay uiteindelijk gewoon alle states aan elkaar vast geschreven.

**Comment by ReinierMaas** [comment]
Het staat op de drive zodat we makkelijker er samen aan kunnen werken

**Comment by ReinierMaas** [comment]
Ik ga het technical van alle sensoren die wij gebruiken schrijven

**Comment by ReinierMaas** [comment]
Ik begin bij sensoren
