### ISSUE TITLE
implement the distance sensor

### ISSUE THREAD

**Issue by Kipke** [Kipke/InteractieTech#5]

**Comment by Kipke** [comment]
It would be very easy to just use [this code](https://code.google.com/p/arduino-new-ping/wiki/Ping_Event_Timer_Sketch) to implement an interrupt based distance sensor. However this system does use two pins and it disables PWM on pin 3 and 11.

So I propose to move the screenLED from pin 3 to 5 and the redPin from pin 11 to 6. The movement sensor can then use pin 7 and 11.

Agree?

**Comment by ReinierMaas** [comment]
Connect it to pin 3 and use my new code that will probably work
