### ISSUE TITLE
implement MovementSensor interrupt

### ISSUE THREAD

**Issue by ReinierMaas** [Kipke/InteractieTech#8]

**Comment by Kipke** [comment]
~~@ReinierMaas It would be very easy to just use [this code](https://code.google.com/p/arduino-new-ping/wiki/Ping_Event_Timer_Sketch) to implement an interrupt based distance sensor. However this system does use two pins and it disables PWM on pin 3 and 11.~~

~~So I propose to move the screenLED from pin 3 to 5 and the redPin from pin 11 to 6. The movement sensor can then use pin 7 and 11.~~

~~Agree?~~

That Comment is obviously meant for the distance sensor, whoops!

**Comment by Kipke** [comment]
Closed in 1a8e10e3165db31ab9baceb89c508158b96272be
